name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branch anpassen, je nachdem welcher Branch die statischen Dateien enthält

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy to GitHub Pages
        run: |
          npm install  # Installieren Sie hier Ihre Abhängigkeiten, falls erforderlich
          npm run build  # Bauen Sie hier Ihre statischen Dateien

          mkdir -p dist
          cp -r Main/public/* dist/  # Kopieren Sie die statischen Dateien in ein dist-Verzeichnis

          # Konfigurieren Sie hier Ihre GitHub Pages
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Veröffentlichen Sie die statischen Dateien auf GitHub Pages
          git checkout gh-pages  # Stellen Sie sicher, dass der Branch gh-pages existiert
          mv -f dist/* .
          git add .
          git commit -m "Deploying to GitHub Pages"
          git push origin gh-pages  # Pushen Sie die Änderungen zum Bereitstellen

