name: Start and Test Server

on:
  workflow_dispatch:  # Manuelle Ausführung des Workflows

jobs:
  start-and-test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Start server in background
        run: node server.js &
        working-directory: ./server

      - name: Wait for server to start
        run: |
          sleep 10  # Wartezeit, damit der Server starten kann

          # Optional: Zeigen Sie die URL an, unter der der Server erreichbar ist
          echo "Server running at http://localhost:3000/"

      - name: Open browser for testing
        run: |
          # Öffnen Sie den Browser für die Testseite (ersetzen Sie die URL entsprechend)
          echo "Öffnen Sie Ihren Browser und navigieren Sie zu http://localhost:3000/"

      - name: Wait for manual confirmation
        run: |
          echo "Bitte führen Sie Ihre Tests im Browser durch."
          echo "Wenn Sie fertig sind, beenden Sie den Workflow."

          # Halten Sie den Workflow offen, bis er manuell beendet wird
          sleep infinity

      - name: Stop server
        run: |
          ps aux | grep 'node server.js' | grep -v grep | awk '{print $2}' | xargs kill

